### ISSUE TITLE
Investigate  how new sonatypePrepare task can help us

### ISSUE THREAD

**Issue by octonato** [playframework/play-meta#113]
sbt-sonatype 3.0 has a new task called `sonatypedPrepare`. It opens a staging repo and then reuse it during the release. This is useful for cross compilations. 

We need to investigate how we can use it to improve our releases. They mention that we should only call `sonatypedPrepare` once in a crossbuild. 

And we should make sure that the staging is limit to our build and won't interfere with other open staging repo (like akka or akka-http).

**Comment by dwijnand** [comment]
Have you seen problems related to staging repos?

I've seen it happen in the release of scala/scala-collection-compat where it created about 8 staging repos, but not in the any Play or Lagom releases.

**Comment by renatocaval** [comment]
Yes, I have seen that a few times and @marcospereira as well. 

We have seen the plugin creating two staging repos (one per scala version), then when it needs to promote then, it fails because it doesn't know which one to promote. 

And that happens we need to manually promote in sonatype and then go back to vegemite to push the tags to GitHub.

**Comment by ignasi35** [comment]
related https://github.com/lagom/lagom/pull/2261 and https://github.com/xerial/sbt-sonatype/blob/8f1774c952e005cdce3046380d3aae96b6e7fcce/ReleaseNotes.md

**Comment by mkurz** [comment]
I think we don't have to care about this anymore since we use sbt-ci-release.
