### ISSUE TITLE
Open Collective as the new home

### ISSUE THREAD

**Issue by ennru** [playframework/play-meta#188]
We are considering [Open Collective](https://opencollective.com/opensource) as Play's new fiscal host so that the community can accept donations and manage costs in the public.

@mkurz presented some reasoning for it in [this forum post](https://discuss.lightbend.com/t/on-the-future-of-play-framework/8920/2) and we at Lightbend are positive about this idea. We need to understand the consequences a bit better, though.

- [x] ensure there is a vital ground of contributors in the Play community
- [x] consider legal consequences for Lightbend's obligations 
- [x] get commitment from Lightbend's executive team
- [x] ~public~ statement from Lightbend to customers
- [x] join an Open Collective in the name of https://github.com/playframework/

**Comment by jroper** [comment]
I think this makes sense. It's definitely not just @mkurz that sees this as a good path forward, I have talked to a number of Play contributors in recent weeks that are on board with this. In the end, they are the life of this project, Lightbend can either walk alongside them and the project will flourish, or can stand in their way, and then either the project will fork and flourish in spite of Lightbend, or the project will fizzle because of Lightbend.

This has played out many times in open source projects before. There really is only one path forward that makes sense here. What many people don't get about open source is that an open source project is not defined by its code or real estate, it is first and foremost defined by its people. Open source projects are communities of people working together, communities of people have achieved extraordinary things with or without the code and/or real estate that made up their projects - Hudson/Jenkins shows what happens when a company (Oracle) doesn't understand that.

So, if the people, the contributors that are active today, want Play to go to the Open Collective, it will happen, and it will happen whether Lightbend supports it or not. I don't think Lightbend or its executive team has any choice in this matter, the choice is more about whether we want the PR disaster of having a project forked out from underneath us.

**Comment by ennru** [comment]
I've just created the Open Source Collective "Playframework" https://opencollective.com/playframework

**Comment by ennru** [comment]
The collective got its first major sponsor: @SethTisue

**Comment by ennru** [comment]
I guess we are there now. Good look, Play!
