### ISSUE TITLE
To backport or not backport binary dependencies

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-meta#62]
I've been discussing with @mkurz about when to backport things.
See https://github.com/playframework/playframework/pull/9192

We have previously said that we backport to latest stable (2.7.x) any bug fix that can be cleanly cherry-picked and that doesn't introduce binary compatible changes. 

We have also said that we will only backport lib updates when there is a known security fix. Users can still update downstream libraries whenever they desire.
Alternatively, we could say, each lib update is backported if done automatically. If not, we just discard the backport PR.

I'm opening this issue so we can discuss it with all contributors and come to a consensus.

**Comment by dwijnand** [comment]
It's easier to manage a project if the focus is on one branch, and work on other branches is kept to a minimum of exceptional cases.  The more cases we make for changes in other branches (even with clauses like "and Mergify does the backporting work" and "and we'll close the PR if it fails") and the more branch state we need to bear in mind.

For instance: "Oh, yeah!  We ended up not backporting the bump of foo to 1.8.8 because it had some weird integration spec failure so we just closed it.  But, then, doesn't bar depend on foo?  Maybe we should go back to that PR and make it pass CI.  Oh, btw, foo 1.8.10 is out, so we should try and use that in 2.7.x."

Much easier: work is focused on one branch (master), and only backport security vulnerabilities to all stable version series, and backport bug-fixing and doc-fixing PRs to the previous stable version (while it continues to be considered widely in use).

**Comment by renatocaval** [comment]
I think we all agree with that. Maybe I wasn't clear on the title and description. This is about backporting dependencies updates to the most recent stable branch only.

**Comment by dwijnand** [comment]
> This is about backporting dependencies updates to the most recent stable branch only.

I believe we covered that: only if it's to bring a fix to a known bug.

For example: "we need to backport this Scala version bump to 2.7.x because it fixes that static method forwarders issue on Java 11"

Counter-example: "Oh, look, Hibernate a.b.new is out, let's bump it in master and also backport it".  We agreed not to do the backport part.

**Comment by dwijnand** [comment]
I guess we'll continue to not have an agreed strategy on this until we come back to it.
